# --- Base manifest values ---
nameOverride: "devops-api"
fullnameOverride: "devops-api"
autoscaling:
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
serviceAccount:
  create: true
  automount: false
  annotations:
    kubernetes.io/automount-service-account-token: "false"
image:
  repository: d4rkghost47/gitops-api
  pullPolicy: IfNotPresent
  tag: "9e41f260"
imagePullSecrets: []
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"
  seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
podLabels: {}
podSecurityContext:
  fsGroup: 10001
  runAsGroup: 3000
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault
  supplementalGroups: [3000]
  sysctls:
  - name: net.ipv4.ip_unprivileged_port_start
    value: "0"
securityContext:
  privileged: false
  procMount: Default
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
    add:
    - NET_BIND_SERVICE
  seccompProfile:
    type: RuntimeDefault
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  containerPortName: http
  appProtocol: http
  sessionAffinity: None
  publishNotReadyAddresses: false
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
env:
- name: PYTHONUNBUFFERED
  value: "1"
- name: HOME
  value: "/tmp"
- name: PYTHONDONTWRITEBYTECODE
  value: "1"
- name: TMPDIR
  value: "/tmp"
resources:
  limits:
    cpu: "200m"
    memory: "512Mi"
    ephemeral-storage: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "64Mi"
livenessProbe:
  httpGet:
    path: /health
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /health
    port: http
    scheme: HTTP
  failureThreshold: 6
  periodSeconds: 5
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 10"]
terminationGracePeriodSeconds: 30
restartPolicy: Always
dnsPolicy: ClusterFirst
dnsConfig:
  options:
  - name: ndots
    value: "5"
volumes:
- name: tmp
  emptyDir:
    medium: Memory
    sizeLimit: 64Mi
- name: cache
  emptyDir:
    medium: Memory
    sizeLimit: 128Mi
volumeMounts:
- name: tmp
  mountPath: /tmp
  readOnly: false
- name: cache
  mountPath: /var/cache
  readOnly: false
podDisruptionBudget:
  enabled: true
  minAvailable: "50%"
  unhealthyPodEvictionPolicy: AlwaysAllow
# --- Service Monitor Configuration ---
serviceMonitor:
  namespace: monitoring
  labels:
    release: prom
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
# --- Istio Configuration ---
istio:
  gateway:
    enabled: true
    namespace: istio-gateway
    selector:
      istio: gateway
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "api.infraops.us"
    labels: {}
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/hostname: "api.infraops.us"
      external-dns.alpha.kubernetes.io/target: c903dcc9-5c64-4d5c-88e1-ee8632ef4ac0.cfargotunnel.com
      kubernetes.io/ingress.class: "istio"
  virtualService:
    enabled: true
    hosts:
    - "api.infraops.us"
    http:
    - name: primary
      match:
      - uri:
          prefix: "/"
      route:
      - destination:
          subset: stable
          port:
            number: 80
      - destination:
          subset: canary
          port:
            number: 80
      retries:
        attempts: 3
        perTryTimeout: 15s
        retryOn: "gateway-error,connect-failure,refused-stream"
      timeout: 15s
      corsPolicy:
        allowOrigins:
        - exact: "https://api.infraops.us"
        allowMethods:
        - GET
        allowHeaders:
        - authorization
        - content-type
        maxAge: "24h"
      headers:
        response:
          set:
            strict-transport-security: "max-age=31536000; includeSubDomains"
            x-content-type-options: "nosniff"
            x-frame-options: "DENY"
  destinationRule:
    enabled: true
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      connectionPool:
        http:
          maxRequestsPerConnection: 20
          http2MaxRequests: 1000
          maxRetries: 3
      tls:
        mode: ISTIO_MUTUAL
    subsets:
      stable:
        name: stable
      canary:
        name: canary
  sidecar:
    enabled: true
    name: default
    egress:
    - hosts:
      - "./*"
      - "istio-system/*"
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  peerAuthentication:
    enabled: true
    name: default
    mtls:
      mode: PERMISSIVE
  externalServices:
    enabled: true
    jsonplaceholder:
      enabled: true
      name: jsonplaceholder.typicode.com
      hosts:
      - "jsonplaceholder.typicode.com"
      ports:
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS
      location: MESH_EXTERNAL
      destinationRule:
        enabled: true
        name: jsonplaceholder-dr
        host: "jsonplaceholder.typicode.com"
        trafficPolicy:
          tls:
            mode: DISABLE
          loadBalancer:
            simple: ROUND_ROBIN
# - Argo Rollouts Configuration ---
rollout:
  analysisTemplate:
    prometheus:
      address: "http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
  spec:
    steps:
    - analysis:
        templates:
        - templateName: check-jsonplaceholder-api-rate
    - setWeight: 25
    - pause:
        duration: 20s
    - analysis:
        templates:
        - templateName: general-success-rate
        args:
        - name: rollout-pod-hash
          valueFrom:
            podTemplateHashValue: Latest
    - setWeight: 50
    - pause:
        duration: 20s
    - analysis:
        templates:
        - templateName: general-success-rate
        args:
        - name: rollout-pod-hash
          valueFrom:
            podTemplateHashValue: Latest
    - pause:
        duration: 20s
    - setWeight: 75
    - analysis:
        templates:
        - templateName: general-success-rate
        - templateName: external-api-success-rate
        - templateName: external-api-latency-p95
        - templateName: circuit-breaker-state
        args:
        - name: rollout-pod-hash
          valueFrom:
            podTemplateHashValue: Latest
    - setWeight: 100
