{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "generic-rollout.fullname" . }}-dr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.destinationRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ include "generic-rollout.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    {{- with .Values.istio.destinationRule.trafficPolicy }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  subsets:
    {{- range $subsetName, $subsetConfig := .Values.istio.destinationRule.subsets }}
    - name: {{ $subsetConfig.name }}
      labels:
        {{- include "generic-rollout.selectorLabels" $ | nindent 8 }}
      {{- with $subsetConfig.loadBalancer }}
      loadBalancer:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with $subsetConfig.tls }}
      tls:
        {{- toYaml . | nindent 12 }}
      {{- end }}
    {{- end }}
{{- end }}