{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "generic-rollout.fullname" . }}-dr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.destinationRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ include "generic-rollout.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    # Este trafficPolicy es para todo el DestinationRule, no para subsets individuales.
    # Solo lo incluimos si hay configuración aquí en values.yaml
    {{- with .Values.istio.destinationRule.trafficPolicy }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  subsets:
    {{- range $subsetName, $subsetConfig := .Values.istio.destinationRule.subsets }}
    - name: {{ $subsetConfig.name }} # Usamos el campo 'name' de values.yaml
      labels:
        {{- include "generic-rollout.selectorLabels" $ | nindent 8 }} # Output de labels, indentado correctamente bajo labels:
      # === CORRECCIÓN: Listamos explícitamente los campos del subset al nivel correcto ===
      {{- with $subsetConfig.loadBalancer }}
      loadBalancer: # Campo loadBalancer al mismo nivel que labels:
        {{- toYaml . | nindent 12 }} # Indentamos el contenido de loadBalancer
      {{- end }}
      {{- with $subsetConfig.tls }}
      tls: # Campo tls al mismo nivel que labels: y loadBalancer:
        {{- toYaml . | nindent 12 }} # Indentamos el contenido de tls
      {{- end }}
      # Si tienes otros campos específicos de subset en values.yaml (como connectionPool, portLevelSettings)
      # debes añadirlos aquí de forma similar:
      # {{- with $subsetConfig.connectionPool }}
      # connectionPool:
      #   {{- toYaml . | nindent 12 }}
      # {{- end }}
      # =======================================================================
    {{- end }}
{{- end }}