{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "generic-rollout.fullname" . }}-dr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.destinationRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ include "generic-rollout.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
  subsets:
    {{- range $subsetName, $subsetConfig := .Values.istio.destinationRule.subsets }}
    - name: {{ $subsetName }} 
      labels:
        {{- include "generic-rollout.selectorLabels" $ | nindent 8 }} 
      trafficPolicy:
        {{- toYaml $subsetConfig | nindent 8 }} 
    {{- end }}
{{- end }}