{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "generic-rollout.fullname" . }}-vsvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.virtualService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gateways:
  - {{ .Values.istio.gateway.namespace }}/{{ include "generic-rollout.fullname" . }}-gateway
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  http:
    {{- range .Values.istio.virtualService.http }}
    - name: {{ .name }}
      match:
        {{- toYaml .match | nindent 8 }}
      route:
        {{- range .route }}
        - destination:
            host: {{ include "generic-rollout.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local
            subset: {{ .destination.subset }}
            port:
              number: {{ .destination.port.number }}
          {{- if eq .destination.subset "stable" }}
          weight: 100
          {{- else if eq .destination.subset "canary" }}
          weight: 0
          {{- end }}
        {{- end }}
      {{- with .retries }}
      retries:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .timeout }}
      timeout: {{ . }}
      {{- end }}
      {{- with .fault }}
      fault:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .corsPolicy }}
      corsPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .headers }}
      headers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}