apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "generic-rollout.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "generic-rollout.fullname" . }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{ include "generic-rollout.fullname" . }}

  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "generic-rollout.fullname" . }}

  strategy:
    canary:
      canaryMetadata:
        annotations:
          role: {{ .Values.image.tag }}
          version: {{ .Values.image.tag }}
        labels:
          service.istio.io/canonical-revision: {{ .Values.image.tag }}
          service.istio.io/canonical-name: {{ .Values.image.tag }}
          app.kubernetes.io/version: {{ .Values.image.tag }}
          version: {{ .Values.image.tag }}
          role: {{ .Values.image.tag }}

      stableMetadata:
        annotations:
          role: {{ .Values.image.tag }}
          version: {{ .Values.image.tag }}
        labels:
          service.istio.io/canonical-revision: {{ .Values.image.tag }}
          service.istio.io/canonical-name: {{ .Values.image.tag }}
          app.kubernetes.io/version: {{ .Values.image.tag }}
          version: {{ .Values.image.tag }}
          role: {{ .Values.image.tag }}

      trafficRouting:
        istio:
          virtualService:
            name: {{ include "generic-rollout.fullname" . }}-vsvc
            routes:
            {{- range .Values.istio.virtualService.http }}
            - {{ .name }}
            {{- end }}
          destinationRule:
            name: {{ include "generic-rollout.fullname" . }}-dr
            canarySubsetName: {{ .Values.istio.destinationRule.subsets.canary.name }}
            stableSubsetName: {{ .Values.istio.destinationRule.subsets.stable.name }}

      steps:
      - setWeight: 10
      - pause:
          duration: 30s
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 75
      - pause:
          duration: 30s
      - setWeight: 100
