{{- if .Values.istio.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  # Lee el nombre directamente de values.yaml
  name: {{ .Values.istio.peerAuthentication.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.peerAuthentication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # WorkloadSelector para apuntar a los pods de la aplicación
  workloadSelector:
    labels:
      {{- include "generic-rollout.selectorLabels" . | nindent 6 }}
  # Lee la configuración de mtls directamente de values.yaml
  mtls:
    {{- toYaml .Values.istio.peerAuthentication.mtls | nindent 4 }}
{{- end }}