apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-rollout.fullname" . }}-monitor
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "generic-rollout.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    {{- toYaml .Values.serviceMonitor.endpoints | nindent 4 }}
  {{- with .Values.serviceMonitor.interval }}
  interval: {{ . }}
  {{- end }}
  {{- with .Values.serviceMonitor.scrapeTimeout }}
  scrapeTimeout: {{ . }}
  {{- end }}